# Generated by Django 3.1.6 on 2021-02-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_user_number_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_of_likes',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
